spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/hotel_management_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: system
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
