spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: system
    password: system
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411/
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
